const mockProducts = [
    {
      productId: 1,
      title: 'Abstract Shapes',
      price: 29.99,
      description: 'A collection of abstract shapes in various colors.',
      image: 'https://example.com/images/abstract-shapes.jpg',
      category: 'Art',
      stockQuantity: 15,
      artistName: 'Jane Smith',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      productId: 2,
      title: 'Minimalist Landscape',
      price: 39.99,
      description: 'A serene minimalist landscape with soft colors.',
      image: 'https://example.com/images/minimalist-landscape.jpg',
      category: 'Art',
      stockQuantity: 10,
      artistName: 'John Doe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      productId: 3,
      title: 'Geometric Patterns',
      price: 19.99,
      description: 'A collection of geometric patterns in black and white.',
      image: 'https://example.com/images/geometric-patterns.jpg',
      category: 'Art',
      stockQuantity: 5,
      artistName: 'Emily Johnson',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      productId: 4,
      title: 'Abstract Portraits',
      price: 49.99,
      description: 'Vibrant and expressive abstract portraits.',
      image: 'https://example.com/images/abstract-portraits.jpg',
      category: 'Art',
      stockQuantity: 8,
      artistName: 'Michael Thompson',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      productId: 5,
      title: 'Nature Abstracts',
      price: 24.99,
      description: 'Abstract representations of natural landscapes and elements.',
      image: 'https://example.com/images/nature-abstracts.jpg',
      category: 'Art',
      stockQuantity: 12,
      artistName: 'Sarah Wilson',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      productId: 6,
      title: 'Modern Sculptures',
      price: 79.99,
      description: 'Contemporary and sleek sculptures for modern art enthusiasts.',
      image: 'https://example.com/images/modern-sculptures.jpg',
      category: 'Art',
      stockQuantity: 3,
      artistName: 'Daniel Ramirez',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      productId: 7,
      title: 'Abstract Cityscapes',
      price: 44.99,
      description: 'Dynamic and energetic abstract cityscape paintings.',
      image: 'https://example.com/images/abstract-cityscapes.jpg',
      category: 'Art',
      stockQuantity: 6,
      artistName: 'Sophia Lee',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      productId: 8,
      title: 'Minimalist Portraits',
      price: 54.99,
      description: 'Simplistic and striking portraits with minimal elements.',
      image: 'https://example.com/images/minimalist-portraits.jpg',
      category: 'Art',
      stockQuantity: 9,
      artistName: 'Ryan Anderson',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      productId: 9,
      title: 'Colorful Abstracts',
      price: 35.99,
      description: 'Vibrant and colorful abstract paintings.',
      image: 'https://example.com/images/colorful-abstracts.jpg',
      category: 'Art',
      stockQuantity: 7,
      artistName: 'Olivia Johnson',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      productId: 10,
      title: 'Minimalist Sculptures',
      price: 89.99,
      description: 'Sleek and minimalistic sculptures for contemporary spaces.',
      image: 'https://example.com/images/minimalist-sculptures.jpg',
      category: 'Art',
      stockQuantity: 4,
      artistName: 'Christopher Davis',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      productId: 11,
      title: 'Abstract Landscapes',
      price: 42.99,
      description: 'Abstract interpretations of natural landscapes.',
      image: 'https://example.com/images/abstract-landscapes.jpg',
      category: 'Art',
      stockQuantity: 11,
      artistName: 'Isabella Rodriguez',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      productId: 12,
      title: 'Minimalist Illustrations',
      price: 29.99,
      description: 'Simple and elegant illustrations with a minimalist touch.',
      image: 'https://example.com/images/minimalist-illustrations.jpg',
      category: 'Art',
      stockQuantity: 6,
      artistName: 'Ethan Anderson',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
]
  
  export default mockProducts